modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/ilja615/WorldUpgrade/issues/"
license="Abnormals License"
[[mods]]
modId = "worldupgrade"
version = "1.19.3-0.1"
displayName = "WorldUpgrade"
displayURL = "https://github.com/ilja615/WorldUpgrade"
authors = "ilja615"
credits = "Credit to the people"
description = '''
A mod that upgrades your exploration and adventuring experience and adds much more fun to the world!
New biomes, structures, plants, mobs, loot, and more awaits!
'''