modLoader="javafml" #mandatory
loaderVersion="[31.1]" #mandatory
credits="Credits to the boiz." #optional
[[mods]] #mandatory
modId="worldupgrade" #mandatory
version="0.1" #mandatory
displayName="WorldUpgrade" #mandatory
description='''
A mod that upgrades your exploration and adventuring experience and adds much more fun to the world! New biomes, structures, mobs and minibosses, loot, and more awaits!
'''
