modLoader="javafml" #mandatory
loaderVersion="[31.1]" #mandatory
credits="Credits to the boiz." #optional
[[mods]] #mandatory
modId="worldupgrade" #mandatory
version="0.1" #mandatory
displayName="WorldUpgrade" #mandatory
description='''
A mod that upgrades your exploration experience and adds much more detail to the world!
'''
